# Generated by Django 4.0.6 on 2022-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BMI',
            field=models.IntegerField(),
        ),
    ]
