# Generated by Django 4.0.6 on 2022-07-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Diagnosis',
            field=models.TextField(default='i'),
            preserve_default=False,
        ),
    ]
